# =============================================
#   CONFIGURACION DEL SERVIDOR
# =============================================
server.port=8085

# =============================================
#   CONFIGURACION BASE DE DATOS H2
# =============================================
spring.datasource.url=jdbc:h2:mem:relaciones_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =============================================
#   CONSOLA H2 (acceder en: http://localhost:8085/h2-console)
# =============================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# =============================================
#   CONFIGURACION JPA / HIBERNATE
# =============================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================
#   DATOS DE INICIALIZACION
# =============================================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
